In [1]:
import numpy as np
from sklearn.datasets import load_breast_cancer, load_iris
import tensorflow as tf
from tensorflow.keras import layers

2025-07-09 22:04:55.286714: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
from sklearn.model_selection import train_test_split

# Binary Classification
### Breast Cancer

In [6]:
data = load_breast_cancer()
xData = data['data']
yData = data["target"]

In [8]:
xTrain, xTest, yTrain, yTest = train_test_split(xData, yData, random_state=42)

In [7]:
# normalization
...


In [9]:
input_layer = tf.keras.Input(shape=xTrain.shape[1:])
model = layers.Dense(64, activation="elu")(input_layer)
model = layers.Dropout(0.2)(model)
model = layers.Dense(32, activation='elu')(model)
model = layers.Dropout(0.2)(model)
model = layers.Dense(1, activation='sigmoid')(model)

model = tf.keras.Model(input_layer, model)
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 30)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │         1,984 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,097 (16.00 KB)

 Trainable params: 4,097 (16.00 KB)

 Non-trainable params: 0 (0.00 B)

In [10]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.01), loss=tf.keras.losses.BinaryCrossentropy())

In [11]:
model.fit(xTrain, yTrain, validation_data=(xTest, yTest), epochs=20)

Epoch 1/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 43.1634 - val_loss: 3.5440
Epoch 2/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.5076 - val_loss: 0.9608
Epoch 3/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.3567 - val_loss: 0.8545
Epoch 4/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.8498 - val_loss: 0.6668
Epoch 5/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7168 - val_loss: 0.6733
Epoch 6/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7768 - val_loss: 0.6587
Epoch 7/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6455 - val_loss: 0.6316
Epoch 8/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6202 - val_loss: 0.3646
Epoch 9/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5365 - val_loss: 0.3369
Epoch 10/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5479 - val_loss: 0.2892
Epoch 11/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5273 - val_loss: 0.2583
Epoch 12/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4373 - val_

In [12]:
from sklearn.metrics import classification_report

In [13]:
y_pred = model.predict(xTest)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step 


In [18]:
print(classification_report(yTest, (y_pred > 0.5)))

              precision    recall  f1-score   support

           0       1.00      0.89      0.94        54
           1       0.94      1.00      0.97        89

    accuracy                           0.96       143
   macro avg       0.97      0.94      0.95       143
weighted avg       0.96      0.96      0.96       143



# Multiclass
## CCE
### Iris

In [19]:
data = load_iris()
xData = data['data']
yData = data["target"]

In [21]:
xTrain, xTest, yTrain, yTest = train_test_split(xData, yData, random_state=42)

In [22]:
# normalization
# ....

In [23]:
yTrain

array([0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 0, 0, 1,
       2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 2, 1, 1, 2, 1, 0, 1, 2, 0,
       0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2, 2, 1, 0, 0, 2, 2, 0, 0, 0, 1,
       2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2, 1, 1, 1, 0, 1, 1, 0, 1,
       2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2, 1, 1, 2, 2, 0, 1, 2, 0,
       1, 2])

In [24]:
np.unique(yTrain)

array([0, 1, 2])

In [39]:
input_layer = tf.keras.Input(shape=xTrain.shape[1:])
model = layers.Dense(32, activation="elu")(input_layer)
model = layers.Dropout(0.2)(model)
model = layers.Dense(16, activation='elu')(model)
model = layers.Dropout(0.2)(model)
model = layers.Dense(len(np.unique(yTrain)), activation='softmax')(model)

model = tf.keras.Model(input_layer, model)
model.summary()

Model: "functional_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_4 (InputLayer)      │ (None, 4)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 32)             │           160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_9 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 3)              │            51 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 739 (2.89 KB)

 Trainable params: 739 (2.89 KB)

 Non-trainable params: 0 (0.00 B)

In [40]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.01), loss=tf.keras.losses.CategoricalCrossentropy())

In [30]:
yTrain

array([0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 0, 0, 1,
       2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 2, 1, 1, 2, 1, 0, 1, 2, 0,
       0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2, 2, 1, 0, 0, 2, 2, 0, 0, 0, 1,
       2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2, 1, 1, 1, 0, 1, 1, 0, 1,
       2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2, 1, 1, 2, 2, 0, 1, 2, 0,
       1, 2])

In [41]:
model.fit(xTrain, tf.keras.utils.to_categorical(yTrain), validation_data=(xTest, tf.keras.utils.to_categorical(yTest)), epochs=20)

Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 53ms/step - loss: 1.7196 - val_loss: 1.1603
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.1013 - val_loss: 0.5240
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6845 - val_loss: 0.4418
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6024 - val_loss: 0.3965
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.5094 - val_loss: 0.3605
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.5760 - val_loss: 0.3320
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.4339 - val_loss: 0.2792
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.3520 - val_loss: 0.3071
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.3531 - val_loss: 0.2262
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.3739 - val_loss: 0.2445
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.4050 - val_loss: 0.2130
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.3201 - val_loss: 0.1695
Epoch 13/

In [42]:
y_pred = model.predict(xTest)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


In [47]:
y_pred = np.argmax(y_pred, 1)

In [48]:
print(classification_report(yTest, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      0.91      0.95        11
           2       0.92      1.00      0.96        12

    accuracy                           0.97        38
   macro avg       0.97      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38

